config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  resources :events, only: [:show, :index, :new, :update, :edit, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  validates :start_date, :end_date, :name, :description, presence: true
end

app/models/habit.rb
class Habit < ApplicationRecord
  belongs_to :user

  validates :title, :days, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  validates :date, :content, :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events
  has_many :tasks
  has_many :habits
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @only_todays_events = current_user.events.where.not('start_date <= ? AND end_date >= ?',
                                                        Date.today.midnight,
                                                        Date.tomorrow.midnight)
                                      .order('start_date')
    @all_day_events = current_user.events.where('start_date <= ? AND end_date >= ?',
                                                Date.today.midnight,
                                                Date.tomorrow.midnight)
  end

  def show
    @events = current_user.events.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(params_event)
    @event.user = current_user
    @event.end_date += 1.day if params[:switchvalue] == 'all day'
    if @event.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update(params_event)
    redirect_to root_path
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to root_path
  end

  private

  def params_event
    params.require(:event).permit(:start_date, :end_date, :name, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/events/index.html.erb
<h2><%= Date.today.strftime("%A%d%B") %></h2>

<div class="d-flex flex-column">
  <p class="m-2">Toute la journée :</p>
  <% @all_day_events.order(:start_date).each do |event| %>
    <div class="d-flex alert-primary m-2 pt-3 border border-primary">
      <p><%= event.name %></p>
    </div>
  <% end %>
  <p class="m-2">À venir aujourd'hui :</p>
  <% @only_todays_events.each do |event| %>
    <div class="d-flex alert-warning m-2 pt-3 border border-warning">
      <% if event.start_date <= Date.today.midnight %>
        <p>00H00</p>&nbsp;
        <p> | <%= event.end_date.strftime("%H") %>H<%= event.end_date.strftime("%M") %></p>&nbsp;
      <% elsif event.end_date >= Date.tomorrow.midnight %>
        <p><%= event.start_date.strftime("%H") %>H<%= event.start_date.strftime("%M") %></p>&nbsp;
        <p> | 00H00</p>&nbsp;
      <% else %>
        <p><%= event.start_date.strftime("%H") %>H<%= event.start_date.strftime("%M") %></p>&nbsp;
        <p> | <%= event.end_date.strftime("%H") %>H<%= event.end_date.strftime("%M") %></p>&nbsp;
      <% end %>
      <p><%= event.name %></p>
    </div>
  <% end %>
</div>

<%= link_to "Créer un nouvel evènement", new_event_path %>

app/views/events/new.html.erb
<h1>Créer un nouvel évènement</h1>

<div id="new-event-form">
  <%= simple_form_for (@event) do |f| %>
    <div class="form-input-group">
      <div class="form-input">
        <%= f.input :name, label: false, placeholder:"Titre" %>
      </div>
      <div class="form-input top-bordered">
        <%= f.input :description, label: false, placeholder:"Description" %>
      </div>
    </div>
    <div class="form-input-group">
      <div class="form-input">
        <p>Toute la journée</p>
        <div class="custom-control custom-switch" class="form-input">
          <input type="checkbox" class="custom-control-input" id="customSwitch1">
          <label class="custom-control-label" for="customSwitch1"></label>
          <%= hidden_field_tag 'switchvalue' %>
        </div>
      </div>
      <div class="form-input bordered">
        <p class="label-datepicker">Du</p> &nbsp;&nbsp;&nbsp;
        <%= f.input :start_date, as: :string, required: false, label: false, input_html: {class: "datepicker"} %>
      </div>
      <div class="form-input">
        <p class="label-datepicker">Au</p> &nbsp;&nbsp;&nbsp;
        <%= f.input :end_date, as: :string, required: false, label: false, input_html: {class: "datepicker"} %>
      </div>
    </div>
</div>
    <%= f.submit "Ajouter", class: "submit-form-btn" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyOrganizationApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/flashes' %>

    <div id="main-container">
      <%= yield %>
    </div>

    <%= render 'shared/navbar' %>
  </body>
</html>

app/views/pages/home.html.erb
<h2><%= Date.today.strftime("%A%d%B") %></h2>
<% current_user.events.each do |event| %>
  <h3><%= event.name %></h3>
  <p><%= event.description %></p>
<% end %>

<%= link_to "Créer un nouvel evènement", new_event_path %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar fixed-bottom navbar-light bg-light">
  <i class="far fa-calendar-plus icon-navbar"></i>
  <i class="fas fa-plus" id="plus-navbar"></i>
  <i class="far fa-check-square icon-navbar"></i>
</div>